env:
  es6: true
  node: true
extends:
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: { }
overrides:
  - files:
      - "**/*.spec.js"
      - "**/*.spec.jsx"
    env:
      jest: true
